import { createI18n } from 'vue-i18n'

const messages = {
  zh: {
    app: {
      title: '世界计划角色匹配测试',
      start: '开始测试',
      next: '下一题',
      prev: '上一题',
      viewResult: '查看结果',
      restart: '重新测试',
      share: '分享结果',
      loading: '加载中...',
      resumeDialog: {
        title: '检测到未完成的测试',
        message: '您上次的测试还未完成，是否要继续？',
        continue: '继续测试',
        restart: '重新开始'
      }
    },
    dimensions: {
      extraversion: '外向性',
      agreeableness: '宜人家',
      conscientiousness: '尽责性',
      neuroticism: '神经质',
      openness: '开放性'
    },
    home: {
      resumeDialog: {
        title: '检测到未完成的测试',
        message: '您上次的测试还未完成，是否要继续？',
        cancel: '重新开始',
        continue: '继续测试'
      },
      resultDialog: {
        title: '您近期已进行过测评',
        message: '是否查看最后一次测评结果？',
        dismiss: '不，谢谢',
        view: '查看结果'
      }
    },
    test: {
      loading: '加载中...',
      dimensionPrefix: '维度:'
    },
    start: {
      title: '哪颗心与你共鸣？世界计划角色测试',
      disclaimer: '本测试为粉丝二创作品，完全免费，基于《世界计划 彩色舞台》世界观。\n所有角色版权归属 SEGA、Colorful Palette 等原公司。\n39 题·五维·实验性选项默认开启，可随时取消。',
      nicknameLabel: '昵称',
      nicknameHint: '可以修改它 它将显示在结果页的标题文案中',
      weightedOption: '结果多样化',
      weightedDesc: '加权算法，突出角色独特性',
      weightedNote: '※ 开启后可能影响结果客观性，但能增加低频角色的出现机会。',
      multiResultOption: '多结果显示',
      multiResultDesc: '展示匹配度≥60% 的其他角色',
      startButton: '开始测试',
      footerText1: '这是',
      footerText2: '使用 Vue 3 重构的版本',
      footerGithub: 'GitHub',
      footerText3: '由',
      footerText4: '主导维护。以 GPL v3 License发布',
      footerLinks: {
        originalProject: 'https://github.com/yangzihao1234567/Project-Sekai_Role-test',
        vueVersion: 'https://github.com/YuxiangWang0525/Project-Sekai_Role-test-vue',
        maintainer: 'https://github.com/YuxiangWang0525'
      }
    },
    question: {
      sliderLabel: '请滑动选择你的符合程度',
      prevButton: '上一题',
      nextButton: '下一题',
      viewResultButton: '查看结果'
    },
    chart: {
      otherMatchesTitle: '其他高匹配角色',
      noData: '暂无其他高匹配角色'
    },
    labels: {
      completelyDisagree: '完全不符合',
      somewhatDisagree: '不太符合',
      neutral: '有些符合',
      somewhatAgree: '基本符合',
      completelyAgree: '完全符合'
    },
    results: {
      title: '测试结果',
      matchPercentage: '匹配度',
      characterDescription: '角色介绍',
      otherMatchesTitle: '其他高匹配角色：',
      backButton: '← 返回最佳匹配',
      retryButton: '重新测试',
      shareButton: '分享结果',
      copyright: 'Generated by Project SEKAI Role Test(Vue 3)\nReleased Under GPL v3 License'
    }
  },
  en: {
    app: {
      title: 'Project Sekai Character Matching Test',
      start: 'Start Test',
      next: 'Next',
      prev: 'Previous',
      viewResult: 'View Results',
      restart: 'Restart Test',
      share: 'Share Results',
      loading: 'Loading...',
      resumeDialog: {
        title: 'Unfinished Test Detected',
        message: 'You have an unfinished test. Would you like to continue?',
        continue: 'Continue Test',
        restart: 'Start Over'
      }
    },
    dimensions: {
      extraversion: 'Extraversion',
      agreeableness: 'Agreeableness',
      conscientiousness: 'Conscientiousness',
      neuroticism: 'Neuroticism',
      openness: 'Openness'
    },
    home: {
      resumeDialog: {
        title: 'Unfinished Test Detected',
        message: 'You have an unfinished test. Would you like to continue?',
        cancel: 'Start Over',
        continue: 'Continue Test'
      },
      resultDialog: {
        title: 'Recent Test Found',
        message: 'Would you like to view your last test result?',
        dismiss: 'No, Thanks',
        view: 'View Results'
      }
    },
    test: {
      loading: 'Loading...',
      dimensionPrefix: 'Dimension:'
    },
    start: {
      title: 'Which Heart Resonates With You? Project Sekai Character Test',
      disclaimer: 'This is a fan-created work, completely free, based on the "Project Sekai Colorful Stage" worldview.\nAll character copyrights belong to SEGA, Colorful Palette and other original companies.\n39 questions·Five dimensions·Experimental options enabled by default, can be disabled anytime.',
      nicknameLabel: 'Nickname',
      nicknameHint: 'You can modify it. It will appear in the result page title.',
      weightedOption: 'Result Diversification',
      weightedDesc: 'Weighted algorithm, highlighting character uniqueness',
      weightedNote: '※ May affect result objectivity when enabled, but increases appearance chances of low-frequency characters.',
      multiResultOption: 'Multiple Results Display',
      multiResultDesc: 'Show other characters with match rate ≥60%',
      startButton: 'Start Test',
      footerText1: 'This is a Vue 3 refactored version of',
      footerText2: '',
      footerGithub: 'GitHub',
      footerText3: 'Maintained by',
      footerText4: '. Released under GPL v3 License',
      footerLinks: {
        originalProject: 'https://github.com/yangzihao1234567/Project-Sekai_Role-test',
        vueVersion: 'https://github.com/YuxiangWang0525/Project-Sekai_Role-test-vue',
        maintainer: 'https://github.com/YuxiangWang0525'
      }
    },
    question: {
      sliderLabel: 'Please slide to select your level of agreement',
      prevButton: 'Previous',
      nextButton: 'Next',
      viewResultButton: 'View Results'
    },
    chart: {
      otherMatchesTitle: 'Other High Matches',
      noData: 'No other high matches available'
    },
    labels: {
      completelyDisagree: 'Completely Disagree',
      somewhatDisagree: 'Somewhat Disagree',
      neutral: 'Neutral',
      somewhatAgree: 'Somewhat Agree',
      completelyAgree: 'Completely Agree'
    },
    results: {
      title: 'Test Results',
      matchPercentage: 'Match Percentage',
      characterDescription: 'Character Description',
      otherMatchesTitle: 'Other High Matches:',
      backButton: '← Back to Best Match',
      retryButton: 'Retest',
      shareButton: 'Share Results',
      copyright: 'Generated by Project SEKAI Role Test(Vue 3)\nReleased Under GPL v3 License'
    }
  },
  ja: {
    app: {
      title: 'プロジェクトセカイ キャラクターマッチングテスト',
      start: 'テスト開始',
      next: '次の質問',
      prev: '前の質問',
      viewResult: '結果を見る',
      restart: 'テストをやり直す',
      share: '結果を共有',
      loading: '読み込み中...',
      resumeDialog: {
        title: '未完了のテストが検出されました',
        message: '前回のテストが完了していません。続行しますか？',
        continue: 'テストを続ける',
        restart: '最初からやり直す'
      }
    },
    dimensions: {
      extraversion: '外向性',
      agreeableness: '協調性',
      conscientiousness: '誠実性',
      neuroticism: '神経質性',
      openness: '開放性'
    },
    home: {
      resumeDialog: {
        title: '未完了のテストが検出されました',
        message: '前回のテストが完了していません。続行しますか？',
        cancel: '最初からやり直す',
        continue: 'テストを続ける'
      },
      resultDialog: {
        title: '最近テストを行いました',
        message: '最後のテスト結果を表示しますか？',
        dismiss: 'いいえ、結構です',
        view: '結果を見る'
      }
    },
    test: {
      loading: '読み込み中...',
      dimensionPrefix: '次元:'
    },
    start: {
      title: 'どの心があなたと共鳴する？プロジェクトセカイ キャラクターテスト',
      disclaimer: 'このテストはファンによる二次創作で、完全無料です。「プロジェクトセカイ カラフルステージ」の世界観に基づいています。\nすべてのキャラクターの著作権はSEGA、カラフルパレットなどの元会社に帰属します。\n39問・五次元・実験的オプションはデフォルトで有効、いつでも無効化できます。',
      nicknameLabel: 'ニックネーム',
      nicknameHint: '変更可能です。結果ページのタイトルに表示されます。',
      weightedOption: '結果の多様化',
      weightedDesc: '加重アルゴリズム、キャラクターの独自性を強調',
      weightedNote: '※ 有効にすると結果の客観性に影響する可能性がありますが、低頻度キャラクターの出現機会が増えます。',
      multiResultOption: '複数結果表示',
      multiResultDesc: '一致率≥60% の他のキャラクターを表示',
      startButton: 'テスト開始',
      footerText1: 'これは',
      footerText2: 'の Vue 3 リファクタリング版です',
      footerGithub: 'GitHub',
      footerText3: '',
      footerText4: 'によってメンテナンスされています。GPL v3 ライセンスでリリース',
      footerLinks: {
        originalProject: 'https://github.com/yangzihao1234567/Project-Sekai_Role-test',
        vueVersion: 'https://github.com/YuxiangWang0525/Project-Sekai_Role-test-vue',
        maintainer: 'https://github.com/YuxiangWang0525'
      }
    },
    question: {
      sliderLabel: 'スライドしてあなたの一致度を選択してください',
      prevButton: '前の質問',
      nextButton: '次の質問',
      viewResultButton: '結果を見る'
    },
    chart: {
      otherMatchesTitle: 'その他の高一致キャラクター',
      noData: 'その他の高一致キャラクターはありません'
    },
    labels: {
      completelyDisagree: '全く当てはまらない',
      somewhatDisagree: 'あまり当てはまらない',
      neutral: 'どちらともいえない',
      somewhatAgree: 'やや当てはまる',
      completelyAgree: 'とても当てはまる'
    },
    results: {
      title: 'テスト結果',
      matchPercentage: '一致率',
      characterDescription: 'キャラクター紹介',
      otherMatchesTitle: 'その他の高一致キャラクター：',
      backButton: '← ベストマッチに戻る',
      retryButton: 'テストをやり直す',
      shareButton: '結果を共有',
      copyright: 'Generated by Project SEKAI Role Test(Vue 3)\nReleased Under GPL v3 License'
    }
  }
}

export const i18n = createI18n({
  legacy: false,
  locale: 'zh',
  fallbackLocale: 'en',
  messages
})

// 语言切换函数
export function switchLanguage(locale: 'zh' | 'en' | 'ja') {
  i18n.global.locale.value = locale
  localStorage.setItem('preferred-language', locale)
}

// 获取保存的语言设置
export function getSavedLanguage(): 'zh' | 'en' | 'ja' {
  const saved = localStorage.getItem('preferred-language')
  if (saved && ['zh', 'en', 'ja'].includes(saved)) {
    return saved as 'zh' | 'en' | 'ja'
  }
  return 'zh'
}
